# Generated by Django 5.2.1 on 2025-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='inherited_from',
        ),
        migrations.AddField(
            model_name='role',
            name='inherited_roles',
            field=models.ManyToManyField(blank=True, to='roles.role'),
        ),
    ]
